
# 指定环境
#spring:
#  profiles:
#    active: dev

server:
  port: 8701
  servlet:
    context-path: / # 访问项目前缀

# 数据库
spring:
  datasource:
    url: jdbc:mysql://192.168.10.67:3306/ant?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
        initial-size: 10
        min-idle: 10
        max-active: 50
        max-wait: 5000
        time-between-eviction-runs-millis: 60000         #1分钟（1.0.14）    有两个含义：
        min-evictable-idle-time-millis: 300000           #30分钟（1.0.14）    连接保持空闲而不被驱逐的最长时间
        test-while-idle: true                            #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
        test-on-borrow: false                            #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        test-on-return: false                            #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
        validation-query: select 1                       #用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
        validation-query-timeout: 1                      #单位：秒，检测连接是否有效的超时时间。底层调用jdbc Statement对象的void setQueryTimeout(int seconds)方法
        pool-prepared-statements: false                  #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭
        connection-init-sqls: set names utf8mb4
        max-open-prepared-statements: -1
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  # redis配置
  redis:
    database: 0 # 使用第1个数据库，一共默认有10个(0-15)
    host: 192.168.10.68
    port: 6379
    jedis:
      pool:
        max-wait: -1
        max-active: 8
        max-idle: 8
        min-idle: 5
    timeout: 5000
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB

security:
  basic:
    enabled: false
management:
  security:
    enabled: false

# 指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:dao/*.xml
  configuration:
    call-setters-on-nulls: true
    cache-enabled: false
    lazy-loading-enabled: false




