# 指定环境
#spring:
#  profiles:
#    active: dev

server:
  port: 8601
  servlet:
    context-path: / # 访问项目前缀

# 数据库
spring:
  datasource:
    url: jdbc:mysql://192.168.10.67:3306/ant?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root

  # redis配置
  redis:
    database: 0 # 使用第1个数据库，一共默认有10个(0-15)
    host: 192.168.10.68
    port: 6379
    jedis:
      pool:
        max-wait: -1
        max-active: 8
        max-idle: 8
        min-idle: 5
    timeout: 5000
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB

security:
  basic:
    enabled: false
management:
  security:
    enabled: false

# 指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:dao/*.xml
  configuration:
    call-setters-on-nulls: true
    cache-enabled: false
    lazy-loading-enabled: false




